# Generated by Django 2.2.5 on 2019-09-03 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thingsdone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingdone',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thingsdone.Day'),
        ),
        migrations.AddField(
            model_name='thingdone',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thingsdone.Month'),
        ),
        migrations.AddField(
            model_name='thingdone',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thingsdone.Week'),
        ),
    ]
