# Generated by Django 2.2.5 on 2019-09-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thingsdone', '0002_auto_20190903_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingdone',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Trivial'), (2, 'Normal'), (3, 'Challenging'), (4, 'Tough')], default=1, help_text='How challenging was the task?'),
        ),
        migrations.AddField(
            model_name='thingdone',
            name='name',
            field=models.CharField(default='Saikang', help_text='What did you do?', max_length=200),
        ),
    ]
