# Generated by Django 2.2.5 on 2019-09-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thingsdone', '0003_auto_20190903_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thingdone',
            options={'ordering': ['name'], 'verbose_name_plural': 'Things done'},
        ),
    ]
