# Generated by Django 2.2.5 on 2019-09-04 12:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thingsdone', '0004_auto_20190903_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.DateField(default=datetime.date(2019, 9, 4)),
        ),
        migrations.AddField(
            model_name='month',
            name='start_day',
            field=models.DateField(default=datetime.date(2019, 9, 4)),
        ),
        migrations.AddField(
            model_name='thingdone',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='week',
            name='start_day',
            field=models.DateField(default=datetime.date(2019, 9, 4)),
        ),
    ]
