# Generated by Django 2.2.5 on 2019-09-05 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thingsdone', '0009_auto_20190905_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='start_day',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='start_day',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
