# Generated by Django 2.2.5 on 2019-09-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thingsdone', '0013_auto_20190906_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingdone',
            name='difficulty',
            field=models.CharField(choices=[('Trivial', 'Trivial'), ('Normal', 'Normal'), ('Challenging', 'Challenging'), ('Tough', 'Tough')], default='Normal', help_text='How challenging was the task?', max_length=200),
        ),
    ]
